minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "sunrise"

# Site Settings
locale: "en-US"
title: "Machine Learning Demystified"
title_separator: "-"
subtitle: # site tagline that appears below site title in masthead
name: "Avinash Nanda"
description: "Demystifying Data Science concepts."
url: "https://avinash-ml.github.io/"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "avinash-ml/avinash-ml.github.io"
teaser: "/assets/images/image3.jpg"
logo: "/assets/images/logo.png"
masthead_title: "Exploring AI"
breadcrumbs: false # false # true, false (default)
words_per_minute: 200

# bing_site_verification:
# yandex_site_verification:
# naver_site_verification:

# SEO and Analytics
google_site_verification : "RGKPrX6tXIfNIxfJFktjotKa7u8HZyK-VIxj3_3nQp0"
bing_site_verification   : "3723D554A58855A4A1E9041BCF554EED"
# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-175522841-1"
    anonymize_ip: false # default


reCaptcha:
  enabled: true
  siteKey: "6Le_m78ZAAAAAKAo-Wcy5dOQa54O1KfETHZnSOQ9"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "JwZI+JlhQuhXFnWfG4aQbRIOE8gndGHrXqG5THfZi59rRmhauskULWZejII67jKxQr5AkzzKAyv2FOziZ8jz626pA0Or2KKxB4XPPzFeKs1uMWnaWEMKpFq/SpiMz8Yvpig9sL+EYf74Fd+anJIchxLkpUpqXSoZXvSCNcsI8xI="


comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
    endpoint  : https://api.staticman.net/v3/entry/github/avinash-ml/avinash-ml.github.io/



# Site Author
author:
  name: "Avinash Nanda"
  avatar: "/assets/images/profile-pic.jpg"
  bio: "Senior Data Scientist **Love!** ML & DL"
  location: "Pune, Maharastra"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/avinash-nanda"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/avinash53651945"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      #url: "https://www.facebook.com/avinash.nanda.73"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avinash-ml"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:avinash1nanda@email.com"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/avinash53651945"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/avinash-ml"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/avinash.nanda.73"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections - enable a collection for use as drafts
collections:
  Machine-Learning: 
    output: true
    permalink: /:categories/:title/
  Computer-Vision:
    output: true
    permalink: /:categories/:title/
  Natural-Language-Processing:
    output: true
    permalink: /:categories/:title/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:

      # _Machine-Learning
  - scope:
      path: ""
      type: Machine-Learning
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      show_date: true
  # _Computer-Vision
  - scope:
      path: ""
      type: Computer-Vision
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      show_date: true
  # _Natural-Language-Processing
  - scope:
      path: ""
      type: Natural-Language-Processing
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      show_date: true
      

