minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "sunrise"

# Site Settings
locale: "en-US"
title: "Machine Learning Demystified"
title_separator: "-"
subtitle: # site tagline that appears below site title in masthead
name: "Avinash Nanda"
description: "Demystifying Data Science concepts."
url: "https://avinash-ml.github.io/"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "avinash-ml/avinash-ml.github.io"
teaser: "/assets/images/image3.jpg"
logo: "/assets/images/logo.png"
masthead_title: "Exploring AI"
breadcrumbs: true # false # true, false (default)
words_per_minute: 200

comments:
  provider: # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname: # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
    issue_term: # "pathname" (default)
  staticman:
    branch: # "master"
    endpoint: # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey:
  secret:
atom_feed:
  path: # blank (default) uses feed.xml
search: true
search_full_content: # true, false (default)
search_provider: # lunr (default), algolia, google
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
# SEO Related
google_site_verification:
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username: avinash53651945
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)

# Site Author
author:
  name: "Avinash Nanda"
  avatar: "/assets/images/profile-pic.jpg"
  bio: "Senior Data Scientist **Love!** ML & DL"
  location: "Pune, Maharastra"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/avinash-nanda"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/avinash53651945"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      #url: "https://www.facebook.com/avinash.nanda.73"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avinash-ml"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:avinash1nanda@email.com"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/avinash53651945"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/avinash-ml"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/avinash.nanda.73"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections - enable a collection for use as drafts
collections:
  Machine-Learning: 
    output: true
    permalink: /:categories/:title/
  Computer-Vision:
    output: true
    permalink: /:categories/:title/
  Natural-Language-Processing:
    output: true
    permalink: /:categories/:title/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date: true


      # _Machine-Learning
  - scope:
      path: ""
      type: Machine-Learning
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _Computer-Vision
  - scope:
      path: ""
      type: Computer-Vision
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _Natural-Language-Processing
  - scope:
      path: ""
      type: Natural-Language-Processing
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

